CREATE DATABASE IF NOT EXISTS locadora DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE locadora;

CREATE TABLE IF NOT EXISTS cliente(
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    data_cadastro DATE NOT NULL,
    endereco VARCHAR(100) NOT NULL,
    complemento VARCHAR(20) NOT NULL,
    cidade VARCHAR(60) NOT NULL,
    estado VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

CREATE TABLE IF NOT EXISTS marca(
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(70) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS modelo(
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(70) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS automovel(
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    placa VARCHAR(50) NOT NULL,
    chassi VARCHAR(70) NOT NULL,
    renavam VARCHAR(70) NOT NULL,
    marca_id BIGINT(20) NOT NULL,
    modelo_id BIGINT(20) NOT NULL,
    FOREIGN KEY (marca_id) REFERENCES automovel(id),
    FOREIGN KEY (modelo_id) REFERENCES automovel(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS locacao(
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    data_locacao DATE NOT NULL,
    kilometragem VARCHAR(50) NOT NULL,
    cliente_id BIGINT(20) NOT NULL,
    automovel_id BIGINT(20) NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES locacao(id),
    FOREIGN KEY (automovel_id) REFERENCES locacao(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;